name: Deploy Hexo to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo + Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli@latest
          npm ci --prefer-offline

      - name: Build Hexo
        run: |
          hexo clean
          rm -rf public/*  # 确保清理残留文件
          hexo generate --debug

      - name: Verify Public Directory
        run: |
          echo "===== 开始检查 public 目录 ====="
          ls -alh ./public
          
          if [ ! -d "./public" ]; then
            echo "❌ 错误：public 目录不存在！"
            exit 1
          fi
          
          if [ -z "$(ls -A ./public)" ]; then
            echo "❌ 错误：public 目录为空！"
            exit 1
          fi
          
          REQUIRED_FILES=("index.html" "404.html" "css" "js")
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -e "./public/$file" ]; then
              echo "❌ 错误：缺少必要文件 $file"
              exit 1
            fi
          done
          
          echo "✅ public 目录验证通过"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./public
          vercel-args: '--prod --confirm'
