name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo + Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Check source directory
        run: ls -la ./source

      - name: Check hexo config
        run: cat ./_config.yml | grep output_dir

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Build Hexo
        run: |
          hexo clean
          hexo generate

      - name: Check public directory
        run: ls -la ./public

      - name: Upload to Vercel
        uses: amondnet/vercel-action@v25.2.0 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./public
