name: Deploy Hexo to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo + Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli@latest
          npm ci --prefer-offline

      - name: Build Hexo
        run: |
          hexo clean
          rm -rf public/*
          hexo generate

      - name: Verify Public Directory
        run: |
          echo "===== 严格验证 public 目录 ====="
          pwd
          ls -al
          
          if [ ! -e "./public" ]; then
            echo "❌ Critical Error: ./public path not exists!"
            exit 1
          fi
          
          if [ ! -d "./public" ]; then
            echo "❌ Critical Error: ./public is not a directory!"
            exit 1
          fi
          
          file_count=$(find ./public -mindepth 1 -maxdepth 1 | wc -l)
          if [ $file_count -eq 0 ]; then
            echo "❌ Critical Error: ./public is empty!"
            exit 1
          fi
          
          if [ ! -f "./public/index.html" ]; then
            echo "❌ Critical Error: index.html missing!"
            exit 1
          fi
          
          echo "✅ 验证通过：public 目录包含 $(du -sh ./public) 数据"
        shell: bash  # 关键修复：禁用严格模式

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./public
          vercel-args: '--prod --confirm --scope=${{ secrets.VERCEL_ORG_ID }}'
          vercel-version: 28.16.11
