name: Deploy Hexo to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo + Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli@latest
          npm ci --prefer-offline

      - name: Build Hexo
        run: |
          hexo clean
          rm -rf public/*
          hexo generate --debug

      - name: Check Public Purity
        run: |
          if [ -f "./public/package.json" ]; then
            echo "❌ 错误：public 目录包含 package.json！"
            exit 1
          fi
          if [ -f "./public/vercel.json" ]; then
            echo "❌ 错误：public 目录包含 vercel.json！"
            exit 1
          fi

      - name: Clean Vercel Cache
        run: |
          npx vercel cache clean --scope=${{ secrets.VERCEL_ORG_ID }} --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./public
          vercel-args: '--prod --yes --no-build --scope=${{ secrets.VERCEL_ORG_ID }}'
          vercel-version: 28.16.11
